import { Product } from "./store-types";

export const DUMMY_PRODUCTS: Product[] = [
	{
		id: "knee-brace-pro",
		name: "Professional Knee Support Brace",
		description:
			"Advanced knee support with adjustable compression for optimal stability during recovery and daily activities.",
		price: 89.99,
		originalPrice: 119.99,
		image: "/placeholder.jpg",
		images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
		category: "Braces & Supports",
		joint: "knee",
		rating: 4.8,
		reviewCount: 127,
		features: [
			"Adjustable compression",
			"Breathable neoprene material",
			"Patella stabilization",
			"Side stabilizers",
			"Machine washable",
		],
		specifications: {
			Material: "Premium neoprene with nylon lining",
			Sizes: "S, M, L, XL, XXL",
			Color: "Black/Blue",
			Weight: "8 oz",
			Warranty: "1 year",
		},
		inStock: true,
		stockCount: 15,
	},
	{
		id: "shoulder-sling-comfort",
		name: "Comfort Plus Shoulder Sling",
		description:
			"Ergonomic shoulder sling designed for post-surgery recovery and injury support with premium padding.",
		price: 45.99,
		image: "/placeholder.jpg",
		images: ["/placeholder.jpg", "/placeholder.jpg"],
		category: "Slings & Immobilizers",
		joint: "shoulder",
		rating: 4.6,
		reviewCount: 89,
		features: [
			"Ergonomic design",
			"Premium foam padding",
			"Adjustable straps",
			"Thumb loop",
			"Lightweight",
		],
		specifications: {
			Material: "Breathable mesh with foam padding",
			Sizes: "Universal",
			Color: "Navy Blue",
			Weight: "4 oz",
			Warranty: "6 months",
		},
		inStock: true,
		stockCount: 23,
	},
	{
		id: "back-support-lumbar",
		name: "Lumbar Support Belt Pro",
		description:
			"Professional-grade lumbar support belt for lower back pain relief and posture improvement.",
		price: 67.5,
		originalPrice: 85.0,
		image: "/placeholder.jpg",
		images: [
			"/placeholder.jpg",
			"/placeholder.jpg",
			"/placeholder.jpg",
			"/placeholder.jpg",
		],
		category: "Back Support",
		joint: "back",
		rating: 4.7,
		reviewCount: 156,
		features: [
			"Dual-pull mechanism",
			"Breathable mesh panel",
			"Removable lumbar pad",
			"Adjustable compression",
			"Discreet under clothing",
		],
		specifications: {
			Material: "Elastic with breathable mesh",
			Sizes: "S/M, L/XL, XXL",
			Color: "Black",
			Weight: "12 oz",
			Warranty: "1 year",
		},
		inStock: true,
		stockCount: 8,
	},
	{
		id: "hip-compression-sleeve",
		name: "Hip Compression Sleeve",
		description:
			"Therapeutic compression sleeve for hip support and pain relief during movement and exercise.",
		price: 34.99,
		image: "/placeholder.jpg",
		images: ["/placeholder.jpg", "/placeholder.jpg"],
		category: "Compression Wear",
		joint: "hip",
		rating: 4.4,
		reviewCount: 64,
		features: [
			"Graduated compression",
			"Moisture-wicking fabric",
			"Seamless construction",
			"Flexible fit",
			"Anti-odor treatment",
		],
		specifications: {
			Material: "Nylon/Spandex blend",
			Sizes: "S, M, L, XL",
			Color: "Black/Gray",
			Weight: "3 oz",
			Warranty: "90 days",
		},
		inStock: true,
		stockCount: 19,
	},
	{
		id: "ankle-stabilizer-sport",
		name: "Sport Ankle Stabilizer",
		description:
			"High-performance ankle stabilizer for athletes and active individuals with superior lateral support.",
		price: 52.99,
		image: "/placeholder.jpg",
		images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
		category: "Sports Medicine",
		joint: "ankle",
		rating: 4.9,
		reviewCount: 203,
		features: [
			"Dual-hinge design",
			"Lace-up closure",
			"Rigid side panels",
			"Moisture-wicking liner",
			"Low-profile design",
		],
		specifications: {
			Material: "Ballistic nylon with rigid stays",
			Sizes: "XS, S, M, L, XL",
			Color: "Black",
			Weight: "10 oz",
			Warranty: "1 year",
		},
		inStock: true,
		stockCount: 12,
	},
	{
		id: "wrist-brace-carpal",
		name: "Carpal Tunnel Wrist Brace",
		description:
			"Ergonomic wrist brace specifically designed for carpal tunnel syndrome relief and prevention.",
		price: 28.99,
		originalPrice: 39.99,
		image: "/placeholder.jpg",
		images: ["/placeholder.jpg", "/placeholder.jpg"],
		category: "Wrist Support",
		joint: "wrist",
		rating: 4.5,
		reviewCount: 91,
		features: [
			"Neutral wrist position",
			"Removable metal splint",
			"Breathable fabric",
			"Adjustable straps",
			"Day/night wear",
		],
		specifications: {
			Material: "Cotton/Polyester blend",
			Sizes: "S, M, L",
			Color: "Beige",
			Weight: "2 oz",
			Warranty: "6 months",
		},
		inStock: true,
		stockCount: 27,
	},
	{
		id: "elbow-compression-sleeve",
		name: "Tennis Elbow Compression Sleeve",
		description:
			"Targeted compression sleeve for tennis elbow, golfer's elbow, and general elbow pain relief.",
		price: 19.99,
		image: "/placeholder.jpg",
		images: ["/placeholder.jpg"],
		category: "Compression Wear",
		joint: "elbow",
		rating: 4.3,
		reviewCount: 78,
		features: [
			"Targeted compression",
			"Silicone grip strips",
			"Lightweight design",
			"Machine washable",
			"Comfortable fit",
		],
		specifications: {
			Material: "Nylon/Spandex/Silicone",
			Sizes: "S, M, L, XL",
			Color: "Black/Blue",
			Weight: "1.5 oz",
			Warranty: "3 months",
		},
		inStock: false,
		stockCount: 0,
	},
	{
		id: "neck-cervical-collar",
		name: "Soft Cervical Collar",
		description:
			"Comfortable cervical collar for neck support and pain relief during recovery from neck injuries.",
		price: 24.99,
		image: "/placeholder.jpg",
		images: ["/placeholder.jpg", "/placeholder.jpg"],
		category: "Neck Support",
		joint: "neck",
		rating: 4.2,
		reviewCount: 45,
		features: [
			"Soft foam construction",
			"Adjustable height",
			"Washable cover",
			"Lightweight",
			"Comfortable wear",
		],
		specifications: {
			Material: "Polyurethane foam with cotton cover",
			Sizes: "S, M, L",
			Color: "White",
			Weight: "3 oz",
			Warranty: "90 days",
		},
		inStock: true,
		stockCount: 16,
	},
	{
		id: "therapy-resistance-bands",
		name: "Professional Resistance Band Set",
		description:
			"Complete set of resistance bands for physical therapy, rehabilitation, and strength training.",
		price: 39.99,
		originalPrice: 59.99,
		image: "/placeholder.jpg",
		images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
		category: "Exercise Equipment",
		joint: "general",
		rating: 4.8,
		reviewCount: 312,
		features: [
			"5 resistance levels",
			"Door anchor included",
			"Comfortable handles",
			"Ankle straps",
			"Exercise guide included",
		],
		specifications: {
			Material: "Natural latex rubber",
			"Resistance Levels": "Light, Medium, Heavy, X-Heavy, XX-Heavy",
			Color: "Multi-color coded",
			Weight: "2 lbs",
			Warranty: "1 year",
		},
		inStock: true,
		stockCount: 31,
	},
	{
		id: "ice-therapy-pack",
		name: "Professional Ice Therapy Pack",
		description:
			"Reusable hot/cold therapy pack for pain relief and inflammation reduction. Flexible when frozen.",
		price: 16.99,
		image: "/placeholder.jpg",
		images: ["/placeholder.jpg", "/placeholder.jpg"],
		category: "Therapy Equipment",
		joint: "general",
		rating: 4.6,
		reviewCount: 129,
		features: [
			"Hot/cold therapy",
			"Flexible when frozen",
			"Reusable gel pack",
			"Soft fabric cover",
			"Various sizes available",
		],
		specifications: {
			Material: "Medical-grade gel",
			Sizes: "Small (6x9), Large (11x14)",
			Color: "Blue",
			Weight: "1.2 lbs",
			Warranty: "6 months",
		},
		inStock: true,
		stockCount: 44,
	},
];

export const JOINT_CATEGORIES = [
	{ value: "all", label: "All Joints", icon: "🔄" },
	{ value: "knee", label: "Knee", icon: "🦵" },
	{ value: "shoulder", label: "Shoulder", icon: "💪" },
	{ value: "back", label: "Back", icon: "🔙" },
	{ value: "hip", label: "Hip", icon: "🏃" },
	{ value: "ankle", label: "Ankle", icon: "🦶" },
	{ value: "wrist", label: "Wrist", icon: "✋" },
	{ value: "elbow", label: "Elbow", icon: "💪" },
	{ value: "neck", label: "Neck", icon: "👤" },
	{ value: "general", label: "General", icon: "🏥" },
];

export const PRODUCT_CATEGORIES = [
	{ value: "all", label: "All Categories" },
	{ value: "Braces & Supports", label: "Braces & Supports" },
	{ value: "Slings & Immobilizers", label: "Slings & Immobilizers" },
	{ value: "Back Support", label: "Back Support" },
	{ value: "Compression Wear", label: "Compression Wear" },
	{ value: "Sports Medicine", label: "Sports Medicine" },
	{ value: "Wrist Support", label: "Wrist Support" },
	{ value: "Neck Support", label: "Neck Support" },
	{ value: "Exercise Equipment", label: "Exercise Equipment" },
	{ value: "Therapy Equipment", label: "Therapy Equipment" },
];
